services:
  app:
    build: .
    ports:
      - "4200:4200"  # Порт, на котором будет доступно ваше приложение
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/OkseiProject?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
        # Монтируем текущую директорию для разработки

  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"  # Порт для доступа к базе данных
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OkseiProject
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d  # Монтируем папку с SQL скриптами

volumes:
  postgres_data: