version: '3.8'

services:
  app:
    build: .
    ports:
      - '4200:4200'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/OkseiProject
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: yarn start:dev

  db:
    image: postgres:13
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OkseiProject
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
