version: '3.8'

services:
  app:
    build: .
    ports:
      - '4200:4200' # Порт, на котором будет доступно ваше приложение
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/OkseiProject?schema=public
    depends_on:
      - db
    volumes:
      - .:/usr/src/app # Монтируем текущую директорию для разработки

  db:
    image: postgres:13
    ports:
      - '5434:5432' # Порт для доступа к базе данных
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: OkseiProject
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняем данные базы данных

volumes:
  postgres_data:
